id: ff290c57-4742-4de7-b3ff-80464ec79bf0
type: web-application
interactions:
- targetId: bb6a0718-dd0a-4258-b951-aa07ba349be1
  type: gateway
  level: container
annotations:
- namespace: c4modeler
  name: position
  value:
    fa866e4c-2eff-47aa-b2e4-95a34b07f82c:
      x: 435.5896302250804
      y: 124.2154379596281
- namespace: c4modeler
  name: boundary
  value:
    x: 140
    y: 375.5
    width: 280
    height: 751
prefix: app
author: CodeArchitects
target: angular@19
architecture: single-page-application
strict: false
name: NewWebApplication
description: Description for NewWebApplication
children:
- id: c1297f01-ced3-479b-9b60-297380d7d074
  type: application
- id: 49eddd2d-15ee-4e67-893c-72d9cba0a6bb
  type: domain
- id: 7286ce73-d51b-4812-bc99-51006fc58290
  type: scenario
